language: rust
rust:
  - nightly
os: linux
dist: xenial

sudo: false

matrix:
  allow_failures:
    - rust: nightly

before_cache:
  - cargo install cargo-tarpaulin -f

script:
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

notifications:
  email:
    - mr.amirka@ya.ru
  slack:
    on_success: always
    on_failure: always
