language: rust
rust:
  - nightly
os: linux
dist: xenial

cache: cargo

sudo: required

before_install:
  - sudo bash ./kcov-install.sh

script:
  # Запуск тестов
  - cargo test
  - sudo kcov --exclude-pattern=/.cargo,/usr/lib --verify ./target/cov ./target/debug/async_fs-*

notifications:
  email:
    - mr.amirka@ya.ru
  slack:
    on_success: always
    on_failure: always
